# Update apt database on first boot (run 'apt-get update').
# Note, if packages are given, or package_upgrade is true, then
# update will be done independent of this setting.
package_update: false
# Upgrade the instance on first boot
# (ie run apt-get upgrade)
package_upgrade: true

disk_setup:
  /dev/sdc:
    table_type: 'mbr'
    layout: true
    overwrite: false

fs_setup:
  - filesystem: 'ext4'
    device: '/dev/sdc'
    overwrite: false

mounts:
 - [ sdc, /data, "auto", "defaults,nofail", "1", "2" ]

# Install additional packages on first boot
packages:
 - git-core

runcmd:
  - 'sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common'
  - 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
  - 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
  - 'sudo apt-get -y update'
  - |
    export AIRFLOW_VERSION=1.9.0
    && export AIRFLOW_HOME=/home/itdsdopswusadmin/airflow
    && mkdir /home/itdsdopswusadmin/airflow
    && export CONFIG_FILE=/home/itdsdopswusadmin/airflow.cfg
    && sudo apt-get install mysql-client  -y
    && sudo apt-get install libmysqlclient-dev -y
    && pip install apache-airflow[crypto,celery,hive,jdbc,mysql]==$AIRFLOW_VERSION
    && pip install celery[redis]==4.1.1
    && yes | mv CONFIG_FILE AIRFLOW_HOME/
#  - 'sudo apt-get -y install docker-ce'
#  - 'sudo docker login --username absitdsdopswusacr001 --password FuYVABYJe/4Sl4CVp6RWszwoKlDbQysw absitdsdopswusacr001.azurecr.io && sudo docker pull absitdsdopswusacr001.azurecr.io/com.albertsons.itds/docker-airflow:1.0.0-SNAPSHOT'

# final_message
# default: cloud-init boot finished at $TIMESTAMP. Up $UPTIME seconds
# this message is written by cloud-final when the system is finished
# its first boot
final_message: "Airflow server is finally up, after $UPTIME seconds"